---
name: Build & Publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  set-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Set version depending on tag or commit hash
        id: tag
        run: |
          if [ v = "${GITHUB_REF_NAME::1}" ]
          then
            echo "version=${GITHUB_REF_NAME:1}"
          else
            echo "version=${GITHUB_SHA::7}"
          fi >> $GITHUB_OUTPUT

  build-library:
    runs-on: ubuntu-latest
    needs: [ set-version ]
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.14
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish with Gradle
        run: ./gradlew -Pversion="${{ env.VERSION }}" publish
        env:
          VERSION: ${{ needs.set-version.outputs.version }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
